package com.msvc.dal.model;

import java.util.List;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "INGEST_XACTION_EVENT")
public class IngestXactionEvent {
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String eventUuid;
	
	private String ingestObjectEventUuid;
	
	private Long ingestionTimestamp;
	
	private String templateName;
	
	private Integer nbrRecords;
	
	private Integer nbrExceptions;
	
	private String exceptionCode;
	
	private String exceptionDescription;
	
	private String masterMemberRecordUuid;
	
	private int totalNbrStored;
	private int totalNbrExceptions;
	private int totalTransactionProcessed;
	
	@DynamoDBAttribute
	private List<Data> record;
	
	public String getEventUuid() {
		return eventUuid;
	}

	public void setEventUuid(String eventUuid) {
		this.eventUuid = eventUuid;
	}

	public String getIngestObjectEventUuid() {
		return ingestObjectEventUuid;
	}

	public void setIngestObjectEventUuid(String ingestObjectEventUuid) {
		this.ingestObjectEventUuid = ingestObjectEventUuid;
	}

	public Long getIngestionTimestamp() {
		return ingestionTimestamp;
	}

	public void setIngestionTimestamp(Long ingestionTimestamp) {
		this.ingestionTimestamp = ingestionTimestamp;
	}

	public String getTemplateName() {
		return templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public Integer getNbrRecords() {
		return nbrRecords;
	}

	public void setNbrRecords(Integer nbrRecords) {
		this.nbrRecords = nbrRecords;
	}

	public Integer getNbrExceptions() {
		return nbrExceptions;
	}

	public void setNbrExceptions(Integer nbrExceptions) {
		this.nbrExceptions = nbrExceptions;
	}

	public String getExceptionCode() {
		return exceptionCode;
	}

	public void setExceptionCode(String exceptionCode) {
		this.exceptionCode = exceptionCode;
	}

	public String getExceptionDescription() {
		return exceptionDescription;
	}

	public void setExceptionDescription(String exceptionDescription) {
		this.exceptionDescription = exceptionDescription;
	}

	public String getMasterMemberRecordUuid() {
		return masterMemberRecordUuid;
	}

	public void setMasterMemberRecordUuid(String masterMemberRecordUuid) {
		this.masterMemberRecordUuid = masterMemberRecordUuid;
	}
	

	public List<Data> getRecord() {
		return record;
	}

	public void setRecord(List<Data> record) {
		this.record = record;
	}
	
	public int getTotalNbrStored() {
		return totalNbrStored;
	}

	public void setTotalNbrStored(int totalNbrStored) {
		this.totalNbrStored = totalNbrStored;
	}

	public int getTotalNbrExceptions() {
		return totalNbrExceptions;
	}

	public void setTotalNbrExceptions(int totalNbrExceptions) {
		this.totalNbrExceptions = totalNbrExceptions;
	}

	public int getTotalTransactionProcessed() {
		return totalTransactionProcessed;
	}

	public void setTotalTransactionProcessed(int totalTransactionProcessed) {
		this.totalTransactionProcessed = totalTransactionProcessed;
	}

	@Override
	public String toString() {
		return "IngestXactionEvent [eventUuid=" + eventUuid + ", ingestObjectEventUuid=" + ingestObjectEventUuid
				+ ", ingestionTimestamp=" + ingestionTimestamp + ", templateName=" + templateName + ", nbrRecords="
				+ nbrRecords + ", nbrExceptions=" + nbrExceptions + ", exceptionCode=" + exceptionCode
				+ ", exceptionDescription=" + exceptionDescription + ", masterMemberRecordUuid="
				+ masterMemberRecordUuid + ", totalNbrStored=" + totalNbrStored + ", totalNbrExceptions="
				+ totalNbrExceptions + ", totalTransactionProcessed=" + totalTransactionProcessed + ", record=" + record
				+ "]";
	}

	

	
	
}
